name: my-python-buddy-notebook
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asgiref=3.9.1
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - django=5.2.6
  - ld_impl_linux-64=2.44
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.41.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openssl=3.5.2
  - pip=25.2
  - python=3.10.18
  - readline=8.2
  - setuptools=80.9.0
  - sqlparse=0.5.3
  - tk=8.6.13
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - pip:
      - accelerate==1.11.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - autoflake==2.3.1
      - autoimport==1.6.1
      - autopep8==2.3.2
      - babel==2.17.0
      - bandit==1.8.6
      - beautifulsoup4==4.14.2
      - black==25.9.0
      - bleach==6.3.0
      - boltons==21.0.0
      - bracex==2.6
      - bs4==0.0.2
      - certifi==2025.8.3
      - cffi==2.0.0
      - cfgv==3.4.0
      - channels==4.3.1
      - channels-redis==4.3.0
      - charset-normalizer==3.4.3
      - click==8.1.8
      - click-option-group==0.5.7
      - colorama==0.4.6
      - comm==0.2.3
      - coverage==7.10.7
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - diskcache==5.6.3
      - distlib==0.4.0
      - django-extensions==4.1
      - dodgy==0.2.1
      - dotenv==0.9.9
      - exceptiongroup==1.2.2
      - executing==2.2.1
      - face==24.0.0
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fqdn==1.5.1
      - fsspec==2025.10.0
      - glom==22.1.0
      - googleapis-common-protos==1.70.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.1
      - huggingface-hub==0.36.0
      - identify==2.6.14
      - idna==3.10
      - importlib-metadata==8.7.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - isoduration==20.11.0
      - isort==7.0.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.20.0
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - llama-cpp-python==0.3.16
      - maison==1.4.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mcp==1.12.2
      - mdurl==0.1.2
      - mistune==3.1.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - mypy==1.18.2
      - mypy-extensions==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nodeenv==1.9.1
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==2.2.6
      - opentelemetry-api==1.37.0
      - opentelemetry-exporter-otlp-proto-common==1.37.0
      - opentelemetry-exporter-otlp-proto-http==1.37.0
      - opentelemetry-instrumentation==0.58b0
      - opentelemetry-instrumentation-requests==0.58b0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - opentelemetry-util-http==0.58b0
      - overrides==7.7.0
      - packaging==25.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathspec==0.12.1
      - peewee==3.18.2
      - pexpect==4.9.0
      - platformdirs==4.4.0
      - pre-commit==4.3.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==6.32.1
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycodestyle==2.14.0
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pyprojroot==0.3.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytokens==0.2.0
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - redis==6.4.0
      - referencing==0.36.2
      - regex==2025.11.3
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.5.3
      - rpds-py==0.27.1
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.12
      - safetensors==0.6.2
      - semgrep==1.138.0
      - send2trash==1.8.3
      - sh==2.2.2
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - sse-starlette==3.0.2
      - stack-data==0.6.3
      - starlette==0.48.0
      - stevedore==5.5.0
      - sympy==1.14.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomli==2.0.2
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.1
      - types-pyyaml==6.0.12.20250915
      - types-requests==2.32.4.20250913
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - virtualenv==20.34.0
      - vulture==2.14
      - watchfiles==1.1.0
      - wcmatch==8.5.2
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - whitenoise==6.10.0
      - wrapt==1.17.3
      - xdg==6.0.0
      - zipp==3.23.0
