"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

APP_NAME = os.getenv("APP_NAME", "my-python-buddy")
APP_ENV = os.getenv("APP_ENV", "dev")
APP_BUILD = os.getenv("APP_BUILD", "")

# Versioning is now from the VERSION file at the base of the repository
version_path = BASE_DIR / "VERSION"
try:
    with version_path.open("r", encoding="utf-8") as f:
        first_line = f.readline().strip()
    if first_line:
        APP_VERSION = first_line
    else:
        raise ValueError("VERSION file is empty or whitespace-only")
except (FileNotFoundError, PermissionError, IsADirectoryError, UnicodeDecodeError, ValueError):
    APP_VERSION = os.getenv("APP_VERSION", "no-version-detected")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "INSECURE-DUDE-DEV-ONLY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

# Comma-separated list in env, falls back to "*"
ALLOWED_HOSTS = [h for h in os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",") if h]

# Revisit Later: trust origins for CSRF (useful if we’ll access via http://localhost:8000, etc.)
CSRF_TRUSTED_ORIGINS = [o for o in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o]

# Redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Logout users after 30 minutes of being inactive
SESSION_COOKIE_AGE = 30 * 60  # 1800 seconds
SESSION_SAVE_EVERY_REQUEST = True  # refresh expiry on each request

# Session will expire when the browser closes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# HTTPS settings
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Cap request sizes (subject to adjustment as project progresses)
DATA_UPLOAD_MAX_MEMORY_SIZE = 2_000_000  # POST body cap (~2 MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 1_000_000  # In-memory file cap (~1 MB)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'base_application',
]

# Order matters greatly here (AttributeError at / will result)
MIDDLEWARE = [
    # Security first
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise should be early (after Security) to serve static files efficiently
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # Sessions must load before AuthenticationMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Common + CSRF before auth-protected views
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # Populates request.user (must run !BEFORE! base_application/middleware.py)
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Messages used by redirect notices
    'django.contrib.messages.middleware.MessageMiddleware',
    # The custom middleware depends on request.user being present
    "base_application.middleware.ForcePasswordChangeMiddleware",
    # Clickjacking last
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Cache-busted, compressed static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Channels Redis
ASGI_APPLICATION = "core.asgi.application"
# Development
# core/settings.py
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# Production
# CHANNEL_LAYERS = {
#     "default": {"BACKEND": "channels_redis.core.RedisChannelLayer",
#                 "CONFIG": {"hosts": [("127.0.0.1", 6379)]}}
# }
