# Generated by Django 5.2.6 on 2025-09-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedfile',
            name='analysis_analyzers',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='submittedfile',
            name='analysis_findings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submittedfile',
            name='analysis_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not requested'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='NOT_REQUESTED', max_length=20),
        ),
        migrations.AddField(
            model_name='submittedfile',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
