# Generated by Django 5.2.6 on 2025-09-27 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0003_accountprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'analyzer',
                    models.CharField(
                        choices=[('bandit', 'Bandit'), ('semgrep', 'Semgrep'), ('mypy', 'MyPy'), ('vulture', 'Vulture'), ('dodgy', 'Dodgy')],
                        max_length=32,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('NOT_REQUESTED', 'Not Requested'),
                            ('REQUESTED', 'Requested'),
                            ('PENDING', 'Pending'),
                            ('COMPLETED', 'Completed'),
                            ('ERRORED', 'Errored'),
                        ],
                        default='NOT_REQUESTED',
                        max_length=32,
                    ),
                ),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('findings_count', models.IntegerField(default=0)),
                ('submitted_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='base_application.submittedfile')),
            ],
        ),
    ]
