# Generated by Django 5.2.6 on 2025-09-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0004_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='findings_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
