# Generated by Django 5.2.6 on 2025-09-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0005_run_findings_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='severity_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
