# Generated by Django 5.2.6 on 2025-09-29 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0006_run_severity_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='findings_data',
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzer', models.CharField(max_length=32)),
                ('severity', models.CharField(max_length=16)),
                ('rule_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('line', models.IntegerField(blank=True, null=True)),
                ('column', models.IntegerField(blank=True, null=True)),
                ('reference', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='base_application.run')),
            ],
        ),
    ]
