# Generated by Django 5.2.6 on 2025-09-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0007_remove_run_findings_data_finding'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='findings_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Finding',
        ),
    ]
