# Generated by Django 5.2.6 on 2025-09-29 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0010_run_findings_data_delete_finding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveField(
            model_name='run',
            name='findings_data',
        ),
        migrations.AlterField(
            model_name='run',
            name='analyzer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='run',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(
                choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('COMPLETED', 'Completed'), ('ERRORED', 'Errored')],
                default='PENDING',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=20)),
                ('rule_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('line', models.IntegerField()),
                ('column', models.IntegerField(default=0)),
                ('reference', models.URLField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='base_application.run')),
            ],
            options={
                'ordering': ['line', 'column'],
            },
        ),
    ]
