# Generated by Django 5.2.6 on 2025-09-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0011_alter_run_options_remove_run_findings_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='finding',
            unique_together={('run', 'rule_id', 'line', 'column', 'file_hash')},
        ),
    ]
