# Generated by Django 5.2.6 on 2025-10-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0012_finding_file_hash_finding_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='analyzer_version',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='analyzer',
            field=models.CharField(max_length=15),
        ),
    ]
