# Generated by Django 5.2.6 on 2025-10-03 00:34

from django.db import migrations, models

import base_application.models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0013_run_analyzer_version_alter_run_analyzer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='severity_counts',
            field=models.JSONField(blank=True, default=base_application.models.severity_default),
        ),
    ]
