# Generated by Django 5.2.6 on 2025-11-10 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0014_alter_run_severity_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('analyzer', models.CharField(blank=True, max_length=50)),
                ('analyzer_version', models.CharField(blank=True, max_length=25)),
                ('prompt', models.TextField(help_text='User input text')),
                ('response', models.TextField(help_text='Model response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_type', models.CharField(choices=[('search', 'Search'), ('code', 'Code')], default='search', max_length=10)),
                (
                    'run',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='chat_sessions',
                        to='base_application.run',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
