# Generated by Django 5.2.6 on 2025-11-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0015_chatsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedfile',
            name='analysis_analyzers',
        ),
        migrations.RemoveField(
            model_name='submittedfile',
            name='analysis_findings',
        ),
        migrations.RemoveField(
            model_name='submittedfile',
            name='analysis_status',
        ),
    ]
