# Generated by Django 5.2.6 on 2025-11-20 20:21

import django.db.models.deletion
from django.db import migrations, models

import base_application.models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0016_remove_submittedfile_analysis_analyzers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='analyzer',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='analyzer_version',
            field=models.CharField(blank=True, editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='chat_type',
            field=models.CharField(choices=[('search', 'Search'), ('code', 'Code')], default='search', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='file_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='prompt',
            field=models.TextField(editable=False, help_text='User input text'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='response',
            field=models.TextField(editable=False, help_text='Model response'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='column',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='finding',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='file_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='line',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='finding',
            name='message',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='finding',
            name='reference',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='finding',
            name='rule_id',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='finding',
            name='title',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='run',
            name='analyzer',
            field=models.CharField(editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='run',
            name='analyzer_version',
            field=models.CharField(editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='findings_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='severity_counts',
            field=models.JSONField(blank=True, default=base_application.models.severity_default, editable=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(
                choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('COMPLETED', 'Completed'), ('ERRORED', 'Errored')],
                default='PENDING',
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='run',
            name='submitted_file',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='base_application.submittedfile'),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='file',
            field=models.FileField(editable=False, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='original_name',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='saved_name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
