# Generated by Django 5.2.6 on 2025-11-20 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0019_alter_submittedfile_analysis_analyzers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='analyzer',
            field=models.CharField(editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='run',
            name='analyzer_version',
            field=models.CharField(editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='submitted_file',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='base_application.submittedfile'),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='analysis_analyzers',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='analysis_findings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='analysis_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not requested')], default='NOT_REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='original_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='saved_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='sha256',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
