# Generated by Django 5.2.6 on 2025-11-20 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0020_alter_run_analyzer_alter_run_analyzer_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='analyzer',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='run',
            name='analyzer_version',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='submitted_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='base_application.submittedfile'),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='analysis_status',
            field=models.CharField(
                choices=[('NOT_REQUESTED', 'Not requested'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')],
                default='NOT_REQUESTED',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='sha256',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
