# Generated by Django 5.2.6 on 2025-11-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0021_alter_run_analyzer_alter_run_analyzer_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedfile',
            name='analysis_analyzers',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='analysis_findings',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='analysis_status',
            field=models.CharField(
                choices=[('NOT_REQUESTED', 'Not requested'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')],
                default='NOT_REQUESTED',
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='file',
            field=models.FileField(editable=False, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='original_name',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='saved_name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
