# Generated by Django 5.2.6 on 2025-11-20 20:32

import django.db.models.deletion
from django.db import migrations, models

import base_application.models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0022_alter_submittedfile_analysis_analyzers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='analyzer',
            field=models.CharField(editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='run',
            name='analyzer_version',
            field=models.CharField(editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='findings_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='severity_counts',
            field=models.JSONField(blank=True, default=base_application.models.severity_default, editable=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(
                choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('COMPLETED', 'Completed'), ('ERRORED', 'Errored')],
                default='PENDING',
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='run',
            name='submitted_file',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='base_application.submittedfile'),
        ),
    ]
