# Generated by Django 5.2.6 on 2025-11-20 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0023_alter_run_analyzer_alter_run_analyzer_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='submitted_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='base_application.submittedfile'),
        ),
    ]
