# Generated by Django 5.2.6 on 2025-11-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0024_alter_run_submitted_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='analyzer',
            field=models.CharField(max_length=15),
        ),
    ]
