# Generated by Django 5.2.6 on 2025-11-20 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0025_alter_run_analyzer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='column',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='finding',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='file_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='line',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='finding',
            name='message',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='finding',
            name='reference',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='finding',
            name='rule_id',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='finding',
            name='run',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='base_application.run'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='finding',
            name='title',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='run',
            name='analyzer',
            field=models.CharField(editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='run',
            name='submitted_file',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='base_application.submittedfile'),
        ),
    ]
