# Generated by Django 5.2.6 on 2025-11-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0026_alter_finding_column_alter_finding_file_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='analyzer',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='analyzer_version',
            field=models.CharField(blank=True, editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='chat_type',
            field=models.CharField(choices=[('search', 'Search'), ('code', 'Code')], default='search', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='file_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='prompt',
            field=models.TextField(editable=False, help_text='User input text'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='response',
            field=models.TextField(editable=False, help_text='Model response'),
        ),
    ]
